### ISSUE TITLE
Add extended upgrade scenario with realistic product configurations

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#158]
More complicated scenarios that resemble the user’s regular activity on the cluster:

- [ ] Install 1-node cluster of previous LTS version.
- [ ] Expand it to 3 nodes.
- [ ] Upgrade to the current version.
- [ ] Remove a node.
- [ ] Join a node.

Maybe also:

- [ ] Uninstall?

Don't think we've ever tested successful uninstalls in Robotest which we should.

**Comment by wadells** [comment]
> Maybe also:
>     * [ ]  Uninstall?
> 
> Don't think we've ever tested successful uninstalls in Robotest which we should.

I filed https://github.com/gravitational/robotest/issues/187 to track this request, as it isn't really related to upgrade testing, and I'd like to keep issues in this milestone focused on upgrade improvements.

**Comment by wadells** [comment]
I belive we should configure this as a separate test target, so that we still have a "quick" upgrade scenario without the additional complexity this would entail.  I say that because robotest runs can be nondeterministic for a number of reasons, and with increased complexity comes increased chance for non-determinism.  We down the road may want to gate this extended upgrade scenario behind a simpler one.
